# Projekt Supabase powiązany z integracją Vercel
project_id = "tseticasatzviqhthwbr"

[db]
major_version = 15

[auth]
enabled = true
site_url = "https://omni-press.cncsolutions.dev"
additional_redirect_urls = [
  "https://omni-press.cncsolutions.dev/**",
  "https://omni-press.cncsolutions.dev/auth/callback",
  "https://omni-press.cncsolutions.dev/auth/reset-password",
  "https://omni-press.cncsolutions.dev/auth/recover",
  "http://localhost:4321/**",
  "http://localhost:4321/auth/callback",
  "http://localhost:4321/auth/reset-password",
  "http://localhost:4321/auth/recover",
]
