import { adminLayout } from '@/i18n';
import { getSingletonComponentIds } from '@/lib/astro-layout/components';

export function buildLayoutSlotsClientScriptVars(componentOptionsHtml: string) {
	const { fields, actions } = adminLayout;

	return {
		removeSlotLabel: actions.removeSlot,
		variantDefault: adminLayout.variants.default,
		variantAlert: adminLayout.variants.alert,
		styleImage: adminLayout.bannerStyles.image,
		styleText: adminLayout.bannerStyles.text,
		variantBannerDefault: adminLayout.bannerImageVariants.default,
		variantBannerBlue: adminLayout.bannerImageVariants.blue,
		linkCategory: adminLayout.bannerLinkTypes.category,
		linkPage: adminLayout.bannerLinkTypes.page,
		linkExternal: adminLayout.bannerLinkTypes.external,
		componentOptionsHtml,
		componentLabels: adminLayout.componentLabels,
		slotPanelSectionTitleLabel: adminLayout.slotPanelSectionTitleLabel,
		homeFeedCategoriesLabel: adminLayout.homeFeedCategoriesLabel,
		homeFeedCategoriesHint: adminLayout.homeFeedCategoriesHint,
		homeFeedPinnedHint: adminLayout.homeFeedPinnedHint,
		previewChipNoCategories: adminLayout.previewChipNoCategories,
		previewChipCategoriesPrefix: adminLayout.previewChipCategoriesPrefix,
		previewChipPinnedOnly: adminLayout.previewChipPinnedOnly,
		previewChipLinkPrefix: adminLayout.previewChipLinkPrefix,
		moveUp: adminLayout.slotsPreviewMoveUp,
		moveDown: adminLayout.slotsPreviewMoveDown,
		disabledLabel: adminLayout.slotsPreviewDisabled,
		emptyZone: adminLayout.slotsPreviewEmpty,
		singletonComponents: getSingletonComponentIds(),
		certAllLabel: adminLayout.certCategories.all,
		weatherDetailsDisplayModal: adminLayout.weatherDetailsDisplayOptions.modal,
		weatherDetailsDisplayInline: adminLayout.weatherDetailsDisplayOptions.inline,
		weatherDetailsLayoutStacked: adminLayout.weatherDetailsLayoutOptions.stacked,
		weatherDetailsLayoutGrid: adminLayout.weatherDetailsLayoutOptions.grid,
		settingsLabel: adminLayout.slotDialogOpen ?? 'Ustawienia',
		closeLabel: adminLayout.slotDialogClose ?? 'Zamknij',
		fieldLabels: {
			widgetTitle: fields.widgetTitle,
			widgetSectionTitle: fields.widgetSectionTitle,
			widgetLimit: fields.widgetLimit,
			widgetEmptyText: fields.widgetEmptyText,
			widgetHideWhenEmpty: fields.widgetHideWhenEmpty,
			widgetMoreLink: fields.widgetMoreLink,
			widgetVariant: fields.widgetVariant,
			certAdvisoriesCategory: fields.certAdvisoriesCategory,
			bannerStyle: fields.bannerStyle,
			bannerImageUrl: fields.bannerImageUrl,
			bannerImageVariant: fields.bannerImageVariant,
			bannerTextTitle: fields.bannerTextTitle,
			bannerTextButton: fields.bannerTextButton,
			bannerLinkType: fields.bannerLinkType,
			bannerCategory: fields.bannerCategory,
			bannerPage: fields.bannerPage,
			bannerExternalUrl: fields.bannerExternalUrl,
			weatherTerytPowiat: fields.weatherTerytPowiat,
			weatherLat: fields.weatherLat,
			weatherLon: fields.weatherLon,
			weatherMapZoom: fields.weatherMapZoom,
			weatherMapScope: fields.weatherMapScope,
			weatherShowMap: fields.weatherShowMap,
			weatherDetailsDisplay: fields.weatherDetailsDisplay,
			weatherDetailsLayout: fields.weatherDetailsLayout,
			weatherDetailsSummary: fields.weatherDetailsSummary,
			weatherDetailsCloseLabel: fields.weatherDetailsCloseLabel,
			topbarText: fields.topbarText,
			siteMetaName: fields.siteMetaName,
			siteMetaDescription: fields.siteMetaDescription,
			siteMetaUrl: fields.siteMetaUrl,
			headerBrandLogoUrl: fields.headerBrandLogoUrl,
			headerBrandLogoAlt: fields.headerBrandLogoAlt,
			headerBrandHomeHref: fields.headerBrandHomeHref,
			footerContactCtaLabel: fields.footerContactCtaLabel,
			footerContactCtaHref: fields.footerContactCtaHref,
			footerCopyrightSuffix: fields.footerCopyrightSuffix,
		},
	};
}
